"""Xbox kernel (``xboxkrnl.exe``) ordinal → name map.

Azurik imports 151 kernel functions at load time.  Each import is
materialised as a 4-byte slot in the XBE kernel thunk table (at VA
``0x0018F3A0``); the Xbox loader fills each slot with the function's
actual kernel address before ``main`` runs.

For the C-shim platform this table is the *existing* surface area that
shims can reach without any XBE surgery: if a shim calls a kernel
function that's in this list, all we need to emit is an indirect
``JMP [thunk_va]`` stub and the shim's ``call _Foo@N`` relocation
resolves to that stub.  (Adding a NEW kernel import — one Azurik
doesn't already reference — is Phase 2 D1-extend work: the thunk
table has no trailing slack, so it would need a move + re-link of
every existing ``CALL [thunk_va]`` site in the game, which is costly.)

The table below was generated by zipping the thunk-table entries at
VA ``0x18F3A0`` (parsed from the vanilla XBE on disk) against Ghidra's
import pane.  Every (ordinal, name) pair is unique — no aliases.

Each ``KernelOrdinal`` carries:
    ordinal: the xboxkrnl.exe export ordinal.
    name:    the C-facing, un-mangled function name.

Calling convention and argument byte count are intentionally NOT
stored here — the shim's own C extern declaration drives mangling.
The resolver strips the ``_Name@N`` decoration and looks up ``Name``.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class KernelOrdinal:
    """One xboxkrnl.exe export exposed to shims via D1."""
    ordinal: int
    name: str


# ---------------------------------------------------------------------------
# The 151 kernel functions Azurik's vanilla XBE imports, sorted by ordinal.
# ---------------------------------------------------------------------------
# Keep rows sorted by ordinal (ascending) so future audits can binary-
# search.  The `name` column is authoritative; all shim C extern
# declarations must match exactly (case-sensitive).

AZURIK_KERNEL_ORDINALS: tuple[KernelOrdinal, ...] = (
    KernelOrdinal(  1, "AvGetSavedDataAddress"),
    KernelOrdinal(  2, "AvSendTVEncoderOption"),
    KernelOrdinal(  3, "AvSetDisplayMode"),
    KernelOrdinal(  4, "AvSetSavedDataAddress"),
    KernelOrdinal(  8, "DbgPrint"),
    KernelOrdinal( 14, "ExAllocatePool"),
    KernelOrdinal( 15, "ExAllocatePoolWithTag"),
    KernelOrdinal( 16, "ExEventObjectType"),
    KernelOrdinal( 17, "ExFreePool"),
    KernelOrdinal( 22, "ExMutantObjectType"),
    KernelOrdinal( 23, "ExQueryPoolBlockSize"),
    KernelOrdinal( 24, "ExQueryNonVolatileSetting"),
    KernelOrdinal( 30, "ExSemaphoreObjectType"),
    KernelOrdinal( 31, "ExTimerObjectType"),
    KernelOrdinal( 35, "FscGetCacheSize"),
    KernelOrdinal( 37, "FscSetCacheSize"),
    KernelOrdinal( 40, "HalDiskCachePartitionCount"),
    KernelOrdinal( 44, "HalGetInterruptVector"),
    KernelOrdinal( 47, "HalRegisterShutdownNotification"),
    KernelOrdinal( 49, "HalReturnToFirmware"),
    KernelOrdinal( 65, "IoCreateDevice"),
    KernelOrdinal( 67, "IoCreateSymbolicLink"),
    KernelOrdinal( 69, "IoDeleteSymbolicLink"),
    KernelOrdinal( 74, "IoInvalidDeviceRequest"),
    KernelOrdinal( 81, "IoStartNextPacket"),
    KernelOrdinal( 83, "IoStartPacket"),
    KernelOrdinal( 87, "IofCompleteRequest"),
    KernelOrdinal( 95, "KeBugCheck"),
    KernelOrdinal( 97, "KeCancelTimer"),
    KernelOrdinal( 98, "KeConnectInterrupt"),
    KernelOrdinal( 99, "KeDelayExecutionThread"),
    KernelOrdinal(100, "KeDisconnectInterrupt"),
    KernelOrdinal(107, "KeInitializeDpc"),
    KernelOrdinal(109, "KeInitializeInterrupt"),
    KernelOrdinal(113, "KeInitializeTimerEx"),
    KernelOrdinal(119, "KeInsertQueueDpc"),
    KernelOrdinal(124, "KeQueryBasePriorityThread"),
    KernelOrdinal(125, "KeQueryInterruptTime"),
    KernelOrdinal(126, "KeQueryPerformanceCounter"),
    KernelOrdinal(127, "KeQueryPerformanceFrequency"),
    KernelOrdinal(128, "KeQuerySystemTime"),
    KernelOrdinal(129, "KeRaiseIrqlToDpcLevel"),
    KernelOrdinal(137, "KeRemoveQueueDpc"),
    KernelOrdinal(139, "KeRestoreFloatingPointState"),
    KernelOrdinal(142, "KeSaveFloatingPointState"),
    KernelOrdinal(143, "KeSetBasePriorityThread"),
    KernelOrdinal(144, "KeSetDisableBoostThread"),
    KernelOrdinal(145, "KeSetEvent"),
    KernelOrdinal(149, "KeSetTimer"),
    KernelOrdinal(151, "KeStallExecutionProcessor"),
    KernelOrdinal(153, "KeSynchronizeExecution"),
    KernelOrdinal(156, "KeTickCount"),
    KernelOrdinal(157, "KeTimeIncrement"),
    KernelOrdinal(159, "KeWaitForSingleObject"),
    KernelOrdinal(160, "KfRaiseIrql"),
    KernelOrdinal(161, "KfLowerIrql"),
    KernelOrdinal(164, "LaunchDataPage"),
    KernelOrdinal(165, "MmAllocateContiguousMemory"),
    KernelOrdinal(166, "MmAllocateContiguousMemoryEx"),
    KernelOrdinal(167, "MmAllocateSystemMemory"),
    KernelOrdinal(168, "MmClaimGpuInstanceMemory"),
    KernelOrdinal(171, "MmFreeContiguousMemory"),
    KernelOrdinal(172, "MmFreeSystemMemory"),
    KernelOrdinal(173, "MmGetPhysicalAddress"),
    KernelOrdinal(175, "MmLockUnlockBufferPages"),
    KernelOrdinal(176, "MmLockUnlockPhysicalPage"),
    KernelOrdinal(178, "MmPersistContiguousMemory"),
    KernelOrdinal(179, "MmQueryAddressProtect"),
    KernelOrdinal(180, "MmQueryAllocationSize"),
    KernelOrdinal(181, "MmQueryStatistics"),
    KernelOrdinal(182, "MmSetAddressProtect"),
    KernelOrdinal(184, "NtAllocateVirtualMemory"),
    KernelOrdinal(185, "NtCancelTimer"),
    KernelOrdinal(186, "NtClearEvent"),
    KernelOrdinal(187, "NtClose"),
    KernelOrdinal(189, "NtCreateEvent"),
    KernelOrdinal(190, "NtCreateFile"),
    KernelOrdinal(191, "NtCreateIoCompletion"),
    KernelOrdinal(192, "NtCreateMutant"),
    KernelOrdinal(193, "NtCreateSemaphore"),
    KernelOrdinal(194, "NtCreateTimer"),
    KernelOrdinal(196, "NtDeviceIoControlFile"),
    KernelOrdinal(197, "NtDuplicateObject"),
    KernelOrdinal(198, "NtFlushBuffersFile"),
    KernelOrdinal(199, "NtFreeVirtualMemory"),
    KernelOrdinal(200, "NtFsControlFile"),
    KernelOrdinal(202, "NtOpenFile"),
    KernelOrdinal(203, "NtOpenSymbolicLinkObject"),
    KernelOrdinal(204, "NtProtectVirtualMemory"),
    KernelOrdinal(205, "NtPulseEvent"),
    KernelOrdinal(206, "NtQueueApcThread"),
    KernelOrdinal(207, "NtQueryDirectoryFile"),
    KernelOrdinal(210, "NtQueryFullAttributesFile"),
    KernelOrdinal(211, "NtQueryInformationFile"),
    KernelOrdinal(215, "NtQuerySymbolicLinkObject"),
    KernelOrdinal(217, "NtQueryVirtualMemory"),
    KernelOrdinal(218, "NtQueryVolumeInformationFile"),
    KernelOrdinal(219, "NtReadFile"),
    KernelOrdinal(220, "NtReadFileScatter"),
    KernelOrdinal(221, "NtReleaseMutant"),
    KernelOrdinal(222, "NtReleaseSemaphore"),
    KernelOrdinal(223, "NtRemoveIoCompletion"),
    KernelOrdinal(224, "NtResumeThread"),
    KernelOrdinal(225, "NtSetEvent"),
    KernelOrdinal(226, "NtSetInformationFile"),
    KernelOrdinal(227, "NtSetIoCompletion"),
    KernelOrdinal(229, "NtSetTimerEx"),
    KernelOrdinal(230, "NtSignalAndWaitForSingleObjectEx"),
    KernelOrdinal(231, "NtSuspendThread"),
    KernelOrdinal(232, "NtUserIoApcDispatcher"),
    KernelOrdinal(233, "NtWaitForSingleObject"),
    KernelOrdinal(234, "NtWaitForSingleObjectEx"),
    KernelOrdinal(235, "NtWaitForMultipleObjectsEx"),
    KernelOrdinal(236, "NtWriteFile"),
    KernelOrdinal(237, "NtWriteFileGather"),
    KernelOrdinal(238, "NtYieldExecution"),
    KernelOrdinal(243, "ObOpenObjectByName"),
    KernelOrdinal(246, "ObReferenceObjectByHandle"),
    KernelOrdinal(250, "ObfDereferenceObject"),
    KernelOrdinal(255, "PsCreateSystemThreadEx"),
    KernelOrdinal(258, "PsTerminateSystemThread"),
    KernelOrdinal(259, "PsThreadObjectType"),
    KernelOrdinal(260, "RtlAnsiStringToUnicodeString"),
    KernelOrdinal(268, "RtlCompareMemory"),
    KernelOrdinal(269, "RtlCompareMemoryUlong"),
    KernelOrdinal(277, "RtlEnterCriticalSection"),
    KernelOrdinal(279, "RtlEqualString"),
    KernelOrdinal(285, "RtlFillMemoryUlong"),
    KernelOrdinal(286, "RtlFreeAnsiString"),
    KernelOrdinal(289, "RtlInitAnsiString"),
    KernelOrdinal(290, "RtlInitUnicodeString"),
    KernelOrdinal(291, "RtlInitializeCriticalSection"),
    KernelOrdinal(294, "RtlLeaveCriticalSection"),
    KernelOrdinal(301, "RtlNtStatusToDosError"),
    KernelOrdinal(302, "RtlRaiseException"),
    KernelOrdinal(304, "RtlTimeFieldsToTime"),
    KernelOrdinal(305, "RtlTimeToTimeFields"),
    KernelOrdinal(308, "RtlUnicodeStringToAnsiString"),
    KernelOrdinal(312, "RtlUnwind"),
    KernelOrdinal(322, "XboxHardwareInfo"),
    KernelOrdinal(323, "XboxHDKey"),
    KernelOrdinal(325, "XboxSignatureKey"),
    KernelOrdinal(327, "XeLoadSection"),
    KernelOrdinal(328, "XeUnloadSection"),
    KernelOrdinal(335, "XcSHAInit"),
    KernelOrdinal(336, "XcSHAUpdate"),
    KernelOrdinal(337, "XcSHAFinal"),
    KernelOrdinal(356, "HalBootSMCVideoMode"),
    KernelOrdinal(358, "HalIsResetOrShutdownPending"),
    KernelOrdinal(359, "IoMarkIrpMustComplete"),
    KernelOrdinal(360, "HalInitiateShutdown"),
)


# Build lookup dicts up-front — these are the public API most callers
# want (including `kernel_imports.py` and the drift-guard tests).

ORDINAL_TO_NAME: dict[int, str] = {
    e.ordinal: e.name for e in AZURIK_KERNEL_ORDINALS
}
"""All kernel ordinals Azurik imports, mapped to their public name."""


NAME_TO_ORDINAL: dict[str, int] = {
    e.name: e.ordinal for e in AZURIK_KERNEL_ORDINALS
}
"""Inverse of ``ORDINAL_TO_NAME``.  Every (ordinal, name) pair is
unique in Azurik's XBE so this is a clean bijection."""


def ordinal_for(name: str) -> int | None:
    """Return the kernel ordinal that exports ``name``, or ``None``.

    Used by :func:`azurik_mod.patching.kernel_imports.stub_for_symbol`
    to turn a shim's demangled extern into a thunk-table lookup.
    """
    return NAME_TO_ORDINAL.get(name)
