#!/usr/bin/env bash
# Scaffold a new Azurik feature folder.
#
# Usage:
#   shims/toolchain/new_shim.sh <name>
#
# Creates a feature folder at azurik_mod/patches/<name>/ containing:
#
#   azurik_mod/patches/<name>/
#     __init__.py    — Feature(...) declaration referencing shim.c
#     shim.c         — starter C source, empty __stdcall body
#
# Deleting the feature later = removing that one folder.  Compiled
# artifacts land at shims/build/<name>.o (shared cache, keyed on
# pack name so two features whose source both happens to be called
# shim.c don't collide).

set -eu

if [[ $# -lt 1 ]]; then
    echo "usage: $0 <name>" >&2
    echo "   e.g. $0 skip_prophecy" >&2
    exit 64
fi

name="$1"
if [[ ! "$name" =~ ^[a-z][a-z0-9_]*$ ]]; then
    echo "error: name must be lowercase identifier (a-z, 0-9, _)," \
         "starting with a letter.  got: $name" >&2
    exit 65
fi

# Uppercase form for constant names (NAME_TRAMPOLINE).  `tr` is
# portable; bash 4 ${var^^} isn't available on macOS's default /bin/bash.
name_upper=$(printf '%s' "$name" | tr '[:lower:]' '[:upper:]')

repo_root=$(cd "$(dirname "$0")/../.." && pwd)
feature_dir="$repo_root/azurik_mod/patches/$name"
init_py="$feature_dir/__init__.py"
shim_c="$feature_dir/shim.c"

if [[ -e "$feature_dir" ]]; then
    echo "error: $feature_dir already exists; pick a different name" \
         "or edit the existing feature." >&2
    exit 66
fi

mkdir -p "$feature_dir"

# ----------------------------------------------------------------------
# shim.c — use single-quoted heredoc so bash doesn't try to interpret
# the C source, then sed in $name afterwards.
# ----------------------------------------------------------------------
cat > "$shim_c" <<'SHIMEOF'
/* __NAME__ shim - generated by shims/toolchain/new_shim.sh.
 *
 * Replace the body of c___NAME__ below with your actual logic.
 * Keep the __attribute__((stdcall)) annotation unless the trampoline
 * site you are replacing uses a different calling convention -
 * Azurik's engine is overwhelmingly stdcall / cdecl, and the
 * trampoline pipeline assumes the shim pops its own stack args
 * via `ret N` where N equals the number of argument bytes.
 *
 * Available headers:
 *   azurik.h          - struct layouts (CritterData, PlayerInputState)
 *                       and VA anchors.
 *   azurik_vanilla.h  - extern prototypes for vanilla Azurik functions.
 *   azurik_kernel.h   - extern prototypes for the 151 xboxkrnl imports
 *                       Azurik already pulls in.
 *
 * Remove includes your shim does not actually use.
 */
#include "azurik.h"
#include "azurik_vanilla.h"

/* Replace this signature with one matching the site you are hooking.
 * See azurik_mod/patches/qol_skip_logo/shim.c for the __stdcall-style
 * pattern. */
__attribute__((stdcall))
void c___NAME__(void)
{
    /* TODO: implement the shim behaviour here.  Until you do, this
     * is a no-op that returns immediately. */
}
SHIMEOF
sed -i.bak "s/__NAME__/$name/g" "$shim_c" && rm -f "${shim_c}.bak"

# ----------------------------------------------------------------------
# __init__.py — same trick: single-quoted heredoc + sed substitution.
# ----------------------------------------------------------------------
cat > "$init_py" <<'PYEOF'
"""__NAME__ - TODO one-line description.

Generated by shims/toolchain/new_shim.sh.  Fill in the trampoline VA
below (the 5-byte CALL / JMP instruction in the vanilla XBE that
should divert into your shim), then run the full test suite.
"""

from __future__ import annotations

from pathlib import Path

from azurik_mod.patching import (
    ShimSource,
    TrampolinePatch,
    apply_trampoline_patch,
)
from azurik_mod.patching.registry import Feature, register_feature

_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parent.parent.parent

_SHIM = ShimSource(folder=_HERE, stem="shim")


# TODO: fill in the trampoline VA and replaced_bytes from the vanilla
# XBE (use Ghidra / objdump on default.xbe to confirm).  The minimum
# is 5 bytes to fit a rel32 CALL / JMP; longer windows get NOP-padded.
__UPPER__TRAMPOLINE = TrampolinePatch(
    name="__NAME__",
    label="TODO: short human-readable description",
    va=0x00000000,                        # TODO: site VA
    replaced_bytes=b"\x90\x90\x90\x90\x90",  # TODO: real bytes
    shim_object=_SHIM.object_path("__NAME__", _REPO_ROOT),
    shim_symbol="_c___NAME__",
    mode="call",
)


def apply___NAME___patch(xbe_data: bytearray) -> None:
    """Apply the __NAME__ feature to ``xbe_data``."""
    apply_trampoline_patch(
        xbe_data, __UPPER__TRAMPOLINE, repo_root=_REPO_ROOT)


FEATURE = register_feature(Feature(
    name="__NAME__",
    description="TODO: one-paragraph user-facing summary.",
    sites=[__UPPER__TRAMPOLINE],
    apply=apply___NAME___patch,
    default_on=False,
    tags=("TODO",),
    shim=_SHIM,
))


__all__ = [
    "FEATURE",
    "__UPPER__TRAMPOLINE",
    "apply___NAME___patch",
]
PYEOF
sed -i.bak \
    -e "s/__NAME__/$name/g" \
    -e "s/__UPPER__/${name_upper}_/g" \
    "$init_py" && rm -f "${init_py}.bak"

echo "Created feature folder $feature_dir/"
echo "  - shim.c        (starter C source)"
echo "  - __init__.py   (Feature declaration - fill in the TODOs)"
echo
echo "Next steps:"
echo "  1. Fill in the trampoline VA + replaced_bytes in $init_py"
echo "     (use Ghidra on default.xbe to find the site)."
echo
echo "  2. Edit $shim_c with your actual shim body."
echo
echo "  3. Compile the shim:"
echo "       bash shims/toolchain/compile.sh \\"
echo "           $shim_c shims/build/$name.o"
echo "     (auto-compile at apply time also works - just run the tests."
echo "      Set AZURIK_SHIM_NO_AUTOCOMPILE=1 to require a pre-built .o.)"
echo
echo "  4. Inspect the compiled output:"
echo "       objdump -d shims/build/$name.o"
echo
echo "  5. Add a pytest in tests/ that exercises apply/verify."
echo "     Copy tests/test_qol_skip_logo.py as a template."
echo
echo "  6. Update docs/PATCHES.md with an entry for the new feature."
