#!/usr/bin/env bash
# Scaffold a new Azurik shim source file.
#
# Usage:
#   shims/toolchain/new_shim.sh <name>
#
# Creates shims/src/<name>.c pre-filled with a correctly-annotated
# __stdcall empty shim body (the minimum-viable pattern that the
# trampoline pipeline accepts).  After running, the script prints
# a checklist of the follow-up edits you still need to do by hand:
#
#   1. Write the actual shim body in shims/src/<name>.c.
#   2. Compile it: bash shims/toolchain/compile.sh shims/src/<name>.c
#   3. Declare a TrampolinePatch in a pack module under
#      azurik_mod/patches/ with the site VA you want to replace.
#   4. Add a pytest in tests/ that asserts the shim lands correctly.
#
# The template imports both azurik.h (struct layouts, typedefs) and
# azurik_vanilla.h (calls into vanilla Azurik functions).  Remove
# either include if your shim doesn't need it.

set -eu

if [[ $# -lt 1 ]]; then
    echo "usage: $0 <name>" >&2
    echo "   e.g. $0 skip_prophecy" >&2
    exit 64
fi

name="$1"
# Basic sanity: reject non-identifier names so they resolve to sane
# C symbols.
if [[ ! "$name" =~ ^[a-z][a-z0-9_]*$ ]]; then
    echo "error: name must be lowercase identifier (a-z, 0-9, _)," \
         "starting with a letter.  got: $name" >&2
    exit 65
fi

repo_root=$(cd "$(dirname "$0")/../.." && pwd)
src="$repo_root/shims/src/$name.c"

if [[ -e "$src" ]]; then
    echo "error: $src already exists; pick a different name or edit"\
         "the existing file." >&2
    exit 66
fi

cat > "$src" <<EOF
/* $name shim — generated by shims/toolchain/new_shim.sh.
 *
 * Replace the body of c_$name below with your actual logic.  Keep
 * the __attribute__((stdcall)) annotation unless the trampoline
 * site you're replacing uses a different calling convention —
 * Azurik's engine is overwhelmingly stdcall / cdecl, and the
 * trampoline pipeline assumes the shim pops its own stack args
 * via \`ret N\` where N equals the number of argument bytes.
 *
 * Available:
 *   azurik.h          — struct layouts (CritterData, PlayerInputState)
 *   azurik_vanilla.h  — extern prototypes for vanilla Azurik functions
 *                       that can be called from shims (play_movie_fn,
 *                       poll_movie).
 *
 * Remove includes your shim doesn't actually use — the compile step
 * pulls them in via compile.sh's -I flags, but an unused include
 * can hide accidental dependencies from a reader.
 */
#include "azurik.h"
#include "azurik_vanilla.h"

/* Replace this signature with one matching the site you're hooking.
 * See existing shims (shims/src/skip_logo.c for the __stdcall-style
 * pattern) for calling-convention / stack-cleanup examples. */
__attribute__((stdcall))
void c_$name(void)
{
    /* TODO: implement the shim behaviour here.  Until you do, this
     * is a no-op that returns immediately. */
}
EOF

echo "Created $src"
echo
echo "Next steps:"
echo "  1. Edit $src with your shim body."
echo "  2. Compile:"
echo "       bash shims/toolchain/compile.sh $src"
echo "     -> shims/build/$name.o"
echo
echo "  3. Inspect the output to confirm the calling convention and"
echo "     body make sense:"
echo "       objdump -d shims/build/$name.o"
echo
echo "  4. Declare a TrampolinePatch in a pack module in"
echo "     azurik_mod/patches/.  Example:"
echo
echo "       MY_TRAMPOLINE = TrampolinePatch("
echo "           name=\"$name\","
echo "           label=\"What this patch does\","
echo "           va=0xDEADBEEF,  # site VA to trampoline"
echo "           replaced_bytes=bytes([...]),  # 5+ vanilla bytes"
echo "           shim_object=Path(\"shims/build/$name.o\"),"
echo "           shim_symbol=\"_c_$name\","
echo "           mode=\"call\","
echo "       )"
echo
echo "  5. Add a pytest in tests/ that verifies apply/verify works."
echo "     Copy tests/test_qol_skip_logo.py as a starting point."
echo
echo "  6. Update docs/PATCHES.md with a section for the new pack,"
echo "     and add an entry to docs/SHIMS.md 'Phase 3 shims' list"
echo "     if appropriate."
